[package]
name = "batch_rename"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "A simple command line tool for batch rename files."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
